### ISSUE TITLE
pairwise dmg

### ISSUE THREAD

**Issue by jksr** [lhqing/ALLCools#11]
in tmp adata generation step of pairwise_dmg, if cluster names have special characters (eg L2/3 IT) it will cause error.
May need a mapping to internal names and map back once computing finishes.

**Comment by lhqing** [comment]
There will be lots of error like that, a simple solution is don’t use “/“ in your cluster name.

Hanqing

**Comment by lhqing** [comment]
Close for now

**Comment by lhqing** [comment]
1.
