### ISSUE TITLE
Allcools installation process

### ISSUE THREAD

**Issue by travandlee** [lhqing/ALLCools#14]
Process for installing Allcools on 220104

create conda environment from current list of env.yaml

name: allcools
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.7
  - pip
  - jupyter
  - jupyter_contrib_nbextensions
  - pandas
  - seaborn
  - matplotlib
  - pip:
    - papermill

In the newly created environment:

conda install numba 

install with pip:
anndata
scanpy
ALLCools
xarray
pybedtools
dask
leidenalg
plotly
imblearn
openTSNE

conda install r

pip install rpy2

conda install R rpy2

**Comment by lhqing** [comment]
Thank you, Travis! I am going to put on a full installation doc soon next week.

**Comment by lhqing** [comment]
Hi Travis, I am closing this issue, as the installation tutorial has been added to doc: https://lhqing.github.io/ALLCools/start/installation.html

Thanks
