### ISSUE TITLE
one_vs_rest_dmg runs forever

### ISSUE THREAD

**Issue by qslin** [lhqing/ALLCools#37]
Hi Hanqing, 

When I test data with only about 1000 cells and 30k genes, the one_vs_rest_dmg function takes a very long runtime and never ends. Is there any way to speed up the process? I used the exact same Python codes as those at https://lhqing.github.io/ALLCools/cell_level/dmg/02-DifferentiallyMethylatedGenes.html. And I execute the codes in a python notebook.

**Comment by qslin** [comment]
adding if __name__ == '__main__': before running one_vs_rest_dmg solved the issue

**Comment by Lucky777777777777** [comment]
Hello, thank you for your answer. However, when I use **one_vs_rest_dmg** and add the if condition, the same problem still occurs. The program has been running for about four days and is still in progress.

My execution code is as follows. Could you please help check if there are any other problems?

if __name__ == "__main__":
...     print("Start running the task")
...     
...     dmb_table = one_vs_rest_dmg(
...         adata_met.obs,
...         group=anno_col,
...         mcds_paths='merge_chrom20k.mcds',
...         obs_dim=obs_dim,
...         var_dim=var_dim,
...         mc_type=mc_type,
...         top_n=top_n,
...         adj_p_cutoff=adj_p_cutoff,
...         fc_cutoff=fc_cutoff,
...         auroc_cutoff=auroc_cutoff,
...         max_cluster_cells=max_cluster_cells,
...         max_other_fold=max_other_fold,
...         cpu=1
...     )
