### ISSUE TITLE
plotting downsampled categorical data

### ISSUE THREAD

**Issue by jksr** [lhqing/ALLCools#5]
For plotting functions, whenever downsampling is used, following error might occur if the column to plot is categorical and some categories have small counts. 
ValueError: The palette dictionary is missing keys: {'52'}

should run either  `.cat.remove_unused_categories()` or `.astype(str)`

Saw this error in `categorical_scatter` and also some other plotting functions like the one used in merging clusters

**Comment by lhqing** [comment]
@jksr I saw that too, will fix it today, I prefer .cat.remove_unused_categories() because otherwise, adata convert it back to cat again anyway.

**Comment by lhqing** [comment]
should be fixed now
